### ISSUE TITLE
Variable "$input" received an invalid value error

### ISSUE THREAD

**Issue by ilteris1** [TristanWYL/redwood-realworld-example-app#1]
An error occurred while creating the article. 

**Variable "$input" received an invalid value { title: "x", description: "x", body: "x", tagList: [], authorId: 1 }. The required field "slug" of type "String!" was not provided.**

To resolve this issue, I made a modification in the "articles.sdl.ts" file.

```
input CreateArticleInput {
  slug: String 
  title: String!
  description: String!
  body: String!
  authorId: Int!
  tagList: [String]
}
```

 After making the necessary changes in the GraphQL schema file, this command needs to be run manually:

`yarn rw prisma generate`

**Comment by TristanWYL** [comment]
Hi @ilterisisik , thx for raising this up. However, now I am not available for fixing this in near future, as such you are encouraged to create a PR if you wanna fix this.
